# Site settings
title: OpenWorlds, your 3D Universe
email: info@openworlds.org
description: > # this means to ignore newlines until "baseurl:"
  OpenWorlds is an opensource architecture for hosting interactive 3D worlds,
  where citizens or even tourists can build. It is a modernized version of
  the ActiveWorlds universe concept.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openworlds.github.io" # the base hostname & protocol for your site
#twitter_username: ithamar73
github_username:  openworlds

# Build settings
markdown: kramdown
